pmed/v8pp

- build-v8.bat
The batch file looks similar to build-v8.sh. While it's not perfect (for example, the configuration and target architecture are hard-coded), it hopefully makes it easier for developers on Windows to get started.
> Add batch file to build v8 on Windows

- v8pp/json.hpp
> Add inline keyword to json_str() and json_parse()

- v8pp/context.cpp
- v8pp/context.hpp
To be able to use a different v8::ArrayBuffer::Allocator export the pointer as an optional v8pp::context parameter
> Exported v8::ArrayBuffer::Allocator as an optional v8pp::context parameter

- v8pp/class.hpp
- v8pp/convert.hpp
- v8pp/property.hpp
As described in issue #52, turning C++ exceptions thrown from invalid property accesses into V8 exceptions can keep the electron v1.4.15 console from crashing. That is what this PR accomplishes.
> Mitigate electron DevTools console crashes

- v8pp/class.hpp
Adding .inherit() changes the js_function_template() inheritance, which only
has an effect on wrapped classes if class_function_template() inherits
js_function_template() regardless of the presence of ctor.
Signed-off-by: Tim Janik <timj@gnu.org>
> Allow .inherit() to work with classes without ctor()

- v8pp/throw_ex.hpp
- v8pp/throw_ex.ipp
- Added throw_ex function without exception_ctor parameter
- Refactored throw_ex function body to use v8::String::NewFromUtf8 to convert std::string function to v8::Local<v8::String> value. This makes the usage of windows.h obsolete.
> Refactored throw_ex function

- test/test_class.cpp
- v8pp/function.hpp
Previously this was giving a segfault
Fixes #106
> Throw exception when calling method without instance

- README.md
- docs/convert.md
- docs/utilities.md
- docs/wrapping.md
- examples/01 hello world/hello.cc
- examples/02 arguments/addon.cc
- examples/03 callbacks/addon.cc
- examples/04 object factory/addon.cc
- examples/05 function factory/addon.cc
- examples/06 wrapped objects/addon.cc
- examples/06 wrapped objects/myobject.cc
- examples/06 wrapped objects/myobject.h
- examples/07 wrapped objects factory/addon.cc
- examples/08 passing wrapped objects/addon.cc
- v8pp/convert.hpp
- v8pp/persistent.hpp
Fix the remaining v8::Handle occourances, including the docs & examples, so users are not mislead into using deprecated/removed types.
> Use v8::Local handles everywhere

- Makefile
- test/test_class.cpp
- v8pp/class.hpp
Ability to get an `class_<T>` back from "classes" registry so that members can be added after declaration is done. Call is explicit using `class_<T>::extend_class`
> Extend class

- Makefile
- test/test_context.cpp
- v8pp/context.cpp
- v8pp/context.hpp
Using v8 in a multi-threaded environment requires explicit calls to enter and exit the context. 
This patch adds support for asking context to switch to explicit enter/exit pairs (default is still to implicitly Enter the context)
In addition, this patch introduces the context::context_scope class which is an RAII to Enter and Exit the context. When the isolate is owned by the context, in addition to enter the context, it also acquires a v8::Locker and enters the Isolate. 
This means that by acquiring a context_scope you can safely call JS from any thread.
> Support context scopes and explicit enters

- v8pp/context.cpp
- v8pp/function.hpp
The current v8 library does not provide any guarantees about when garbage collection of external objects will be performed, even after the underlying context is destroyed. This can cause issues with tests (valgrind, asan, etc.) and during runtime (especially for large externally-managed objects).
This PR seeks to the implement basic cleanup method [0] during v8pp::context destruction by visiting all objects created with `external_data<T>`, which are derived from a new base class `external_data_base`. This manual destruction incurs a small runtime cost during v8pp::context (including one call to `destroyObjects` and a vtable lookup for each object) but is likely preferable to calling the GC cleanup directly.
The tables below show the before and after results of a leak check of v8pp_test …
> Destroy external objects in context

- test/test.hpp
- test/test_convert.cpp
- v8pp/class.hpp
- v8pp/class.ipp
- v8pp/context.cpp
- v8pp/context.hpp
- v8pp/convert.cpp
- v8pp/convert.hpp
- v8pp/function.hpp
- v8pp/json.hpp
- v8pp/json.ipp
- v8pp/module.hpp
- v8pp/object.hpp
- v8pp/throw_ex.hpp
- v8pp/throw_ex.ipp
- v8pp/utility.hpp
Add `v8pp::basic_string_View` minium required implementation.
> Backport string_view for pre-c++17 compilers

- test/test.hpp
- test/test_convert.cpp
- test/test_utility.cpp
- v8pp/convert.hpp
- v8pp/utility.hpp
Using `detail::is_*` meta-functions in `v8pp::convert<>` implementations, to support other standard containers (i.e. `std::list`, `std::deque`, `std::map`, `std::unordered_map` etc.) between the C++ and V8 values.
> Generic converters for sequence containers, mappings, strings

- test/test_context.cpp
- v8pp/context.cpp
- v8pp/context.hpp
- v8pp/module.hpp
The feature allows to set up the global object at the context creation stage.
module already allows to export functions, modules, classes etc, so we can use modules to setup global object as soon we expose their impl.
> Add support for custom global object in v8pp::context

- test/test_context.cpp
There were a couple of v8 DCHECK assertions related to the isolate not being set in the test when v8::ScriptOrigin needed it, and the Isolate not being cleaned up before shutting down v8. Tested with v8 9.4.146.22.
> Fix test that fails when v8 is built with is_debug and dcheck_always_on

- v8pp/CMakeLists.txt
not sure if it's the best way, but if vcpkg cmake toolchain is used, it defines that property and using a custom findV8 is not required.
> make compatible with installed v8 from vcpkg

- v8pp/CMakeLists.txt
CMAKE_INSTALL_INCLUDEDIR was used before including GNUInstallDirs, causing the first configuration to miss INTERFACE_INCLUDE_DIRECTORIES. Configuring a second time worked, though. Tested with CMake 3.17.5.
I haven't included it here, as I think it might be a breaking change for existing users, but I'd also suggest changing the name of the configuration file from Config.cmake to v8pp-config.cmake or v8ppConfig.cmake, as currently it looks like the config filename needs to be included in the find(). e.g. find_package(v8pp REQUIRED CONFIGS Config.cmake)
For the supported filenames, see the "Config mode" section in https://cmake.org/cmake/help/latest/command/find_package.html#search-modes
> Fix missing INTERFACE_INCLUDE_DIRECTORIES in exported config

- v8pp/call_from_v8.hpp
Add context on what was the expected number of arguments as well as the actual count.
> Make argument count mismatches easier to debug.

- v8pp/context.cpp
- v8pp/context.hpp
Fallback to own implementation for old V8 versions prior to 5.4.
Store created allocator as unique_ptr  in`v8pp::context` to avoid memory leaks.
> Call `NewDefaultAllocator()` for `CreateParams` field

- test/test_class.cpp
... to prevent debug checks in `v8::External::New()` with nullptr values. They are fine as pointers to data members when used in `v8pp::var_()`
> add extra data members in test classes

- test/test_throw_ex.cpp
- v8pp/throw_ex.hpp
- v8pp/throw_ex.ipp
... since V8 version 11.9. Use single `v8pp::throw_ex()` function with optional arguments for exception constructor and options
> allow options in `v8::Exception` ctors

- v8pp/module.hpp
https://github.com/v8/v8/commit/e48c47268c53499814c88c35064d564dbb92e6fd
> handle ObjectTemplate::SetAccessor API change in v8 12.1

- test/CMakeLists.txt
- test/main.cpp
- test/test.hpp
- test/test.vcxproj
- test/test.vcxproj.filters
- test/test_call_from_v8.cpp
- test/test_type_info.cpp
- test/test_utility.cpp
- v8pp/CMakeLists.txt
- v8pp/class.hpp
- v8pp/type_info.hpp
- v8pp/utility.hpp
- v8pp/v8pp.vcxproj
- v8pp/v8pp.vcxproj.filters
... for better modularization.
> extract `v8pp::detail::type_info` into a header file

- v8pp/class.hpp
- v8pp/property.hpp
- v8pp/throw_ex.hpp
- v8pp/throw_ex.ipp
like `throw_error()`, `throw_range_error()`
See #205
> add `throw_ex()` helpers

- CMakeLists.txt
- test/test.hpp
- test/test_call_from_v8.cpp
- test/test_class.cpp
- test/test_context.cpp
- test/test_convert.cpp
- test/test_module.cpp
- test/test_ptr_traits.cpp
- test/test_utility.cpp
- v8pp/call_from_v8.hpp
- v8pp/call_v8.hpp
- v8pp/class.cpp
- v8pp/class.hpp
- v8pp/class.ipp
- v8pp/config.hpp.in
- v8pp/context.hpp
- v8pp/convert.hpp
- v8pp/function.hpp
- v8pp/json.hpp
- v8pp/module.hpp
- v8pp/object.hpp
- v8pp/property.hpp
- v8pp/ptr_traits.hpp
- v8pp/throw_ex.hpp
- v8pp/type_info.hpp
- v8pp/utility.hpp
- v8pp/version.hpp
- additional msvc flag for C++20 in CMakeLists.txt
- add concept `v8pp::detail::WideChar`
- use `std::same_as` concept instead of `std::is_same`
- use `std::is_*_v` constexpr bools
- nested `v8pp::detail` declarations
- use #pragma once instead of include guards
> Enable C++20 

- v8pp/class.hpp
- v8pp/class.ipp
- store object size in `wrapped_object` (0 for externally referenced)
- call `isolate_->AdjustAmountOfExternalAllocatedMemory()` only in `object_registry`: in `wrap_object` and in `reset_object`, to count also implicit copies, wrapped when `auto_wrap_objects` is true
> fix memory accounting for wrapped C++ classes
